services:
  backend:
    build: ./todo_backend
    ports:
      - "8000:8000"
    volumes:
      - ./todo_backend:/app

  frontend:
    build: ./todo_frontend
    ports:
      - "3000:80"
    depends_on:
      - backend
